### ISSUE TITLE
Bungeecord support?

### ISSUE THREAD

**Issue by LimitedGames** [MikroAcse/AutoCommandsPlus#3]
Can you please make this plugin also for Bungeecord use? PLEASE :D

**Comment by MikroAcse** [comment]
What bungeecord support do you want? :)

**Comment by LimitedGames** [comment]
That if you do the plugin in your bungeecord server you can send commands aucomatic to a special server in a special selected time :+1:

**Comment by MikroAcse** [comment]
Just use bungeecord in every single server.
I don't know if I can/want to do this now.
